// 全てこのページでレンダリングされる
// 共通のHTML文を作る

import { AnswerProvider } from "./context/AnswerContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="jp">
      <body>
        <AnswerProvider>{children}</AnswerProvider>
      </body>
    </html>
  );
}
